# Generated by Django 5.1.7 on 2025-03-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_image_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='user',
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
