# Generated by Django 5.1.7 on 2025-03-28 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_alter_image_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('background_image', models.ImageField(upload_to='client_backgrounds/')),
                ('is_default', models.BooleanField(default=False)),
            ],
        ),
    ]
