# Generated by Django 5.1.7 on 2025-03-29 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='qr_code',
            field=models.ImageField(default='/client_backgrounds/DSC04871.jpeg', upload_to='qr_codes/'),
        ),
    ]
