# Generated by Django 5.1.7 on 2025-04-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_client_background_image_alter_image_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
