# Generated by Django 5.1.7 on 2025-04-04 10:25

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_client_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='background_image',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
